baseurl = "https://lushan.me"
languageCode = "en-us"
Title = "Neon"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright lushan"
theme = "hugo_theme_pickles"
custom_css = "/static/css/custom.css"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "lushann"

  # Disqus shortname
  disqus = ""
  # Google Analytics API key.
  ga_api_key = "Your Google Analytics tracking id"


  author = "lushan"
  authorwebsite = "lushan.me"
  avatar = "https://pic1.zhimg.com/80/v2-5f2e129e114b573ce25128ec0f519a46_hd.jpg"
  contact = "Your contact link (ex. mailto:foo@example.com)"
  bio = "Your short bio"
  
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "I was born ready. "
  
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

    
[[menu.main]]
    name = "Pwn"
    url = "/tags/pwn"
    weight = 2

[[menu.main]]
    name = "漏洞分析"
    url = "/tags/漏洞分析"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/pages/about"
    weight = 7

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
